checkpoint_dir: '$ROOT_DIR/src/embedding_preparation/checkpoints/'
log_dir: '$ROOT_DIR/src/embedding_preparation/logs/'
output_save_path: '$ROOT_DIR/src/embedding_preparation/results/'
dataset_dir: '$ROOT_DIR/data/cifar10/'
max_epoch: 500
patience: 50
batch_size: 128
learning_rate: 1e-2
learning_rate_linear: 1e-2
weight_decay: 1e-6
num_workers: 4
dataset: 'cifar10'
contrastive: 'simclr'
random_seed: 2022
