checkpoint_dir: '$ROOT_DIR/src/embedding_preparation/checkpoints/'
log_dir: '$ROOT_DIR/src/embedding_preparation/logs/'
output_save_path: '$ROOT_DIR/src/embedding_preparation/results/'
dataset_dir: '$ROOT_DIR/data/imagenet/'
model: 'resnext50'
max_epoch: 200
patience: 10
batch_size: 64
learning_rate: 1e-3
weight_decay: 1e-8
num_workers: 8
dataset: 'imagenet'
contrastive: 'NA'
random_seed: 1