checkpoint_dir: '$ROOT_DIR/src/embedding_preparation/checkpoints/'
log_dir: '$ROOT_DIR/src/embedding_preparation/logs/'
output_save_path: '$ROOT_DIR/src/embedding_preparation/results/'
dataset_dir: '$ROOT_DIR/data/imagenet/'
model: 'wideresnet50'
max_epoch: 200
patience: 20
batch_size: 128
learning_rate: 1e-4
weight_decay: 1e-4
num_workers: 4
dataset: 'imagenet'
contrastive: 'NA'
random_seed: 1