checkpoint_dir: '$ROOT_DIR/src/embedding_preparation/checkpoints/'
log_dir: '$ROOT_DIR/src/embedding_preparation/logs/'
output_save_path: '$ROOT_DIR/src/embedding_preparation/results/'
dataset_dir: '$ROOT_DIR/data/mnist/'
max_epoch: 300
patience: 30
batch_size: 64
learning_rate: 1e-5
learning_rate_probing: 2e-9
probing_epoch: 1
weight_decay: 1e-8
num_workers: 1
dataset: 'mnist'
contrastive: 'autoencoder'
random_seed: 2022
imsize: 28