checkpoint_dir: '$ROOT_DIR/src/embedding_preparation/checkpoints/'
log_dir: '$ROOT_DIR/src/embedding_preparation/logs/'
output_save_path: '$ROOT_DIR/src/embedding_preparation/results/'
dataset_dir: '$ROOT_DIR/data/mnist/'
max_epoch: 500
patience: 20
batch_size: 128
learning_rate: 2e-6
weight_decay: 5e-4
num_workers: 4
dataset: 'mnist'
contrastive: 'NA'
random_seed: 2022