checkpoint_dir: '$ROOT_DIR/src/embedding_preparation/checkpoints/'
log_dir: '$ROOT_DIR/src/embedding_preparation/logs/'
output_save_path: '$ROOT_DIR/src/embedding_preparation/results/'
dataset_dir: '$ROOT_DIR/data/mnist/'
max_epoch: 500
patience: 50
batch_size: 256
learning_rate: 1e-4
weight_decay: 1e-8
num_workers: 1
dataset: 'mnist'
random_seed: 2022
bad_method: 'wronglabel'
