checkpoint_dir: '$ROOT_DIR/src/embedding_preparation/checkpoints/'
log_dir: '$ROOT_DIR/src/embedding_preparation/logs/'
output_save_path: '$ROOT_DIR/src/embedding_preparation/results/'
dataset_dir: '$ROOT_DIR/data/stl10/'
max_epoch: 300
patience: 15
batch_size: 64
learning_rate: 1e-3
learning_rate_probing: 1e-3
probing_epoch: 10
weight_decay: 1e-8
num_workers: 8
dataset: 'stl10'
contrastive: 'simclr'
random_seed: 2022
