checkpoint_dir: '$ROOT_DIR/src/embedding_preparation/checkpoints/'
log_dir: '$ROOT_DIR/src/embedding_preparation/logs/'
output_save_path: '$ROOT_DIR/src/embedding_preparation/results/'
dataset_dir: '$ROOT_DIR/data/stl10/'
max_epoch: 500
patience: 50
batch_size: 128
learning_rate: 1e-3
weight_decay: 1e-4
num_workers: 4
dataset: 'stl10'
contrastive: 'simclr'
simclr_train_ratio: 0.8
random_seed: 2022