checkpoint_dir: '$ROOT_DIR/src/embedding_preparation/checkpoints/'
log_dir: '$ROOT_DIR/src/embedding_preparation/logs/'
output_save_path: '$ROOT_DIR/src/embedding_preparation/results/'
dataset_dir: '$ROOT_DIR/data/cifar10/'
max_epoch: 300
batch_size: 16
learning_rate: 1e-3
num_workers: 4
dataset: 'cifar10'
method: 'wronglabel'
random_seed: 1