checkpoint_dir: '$ROOT_DIR/src/main_studies/training_dynamic/checkpoints/'
log_dir: '$ROOT_DIR/src/main_studies/training_dynamic/logs/'
output_save_path: '$ROOT_DIR/src/main_studies/training_dynamic/results/'
dataset_dir: '$ROOT_DIR/data/mnist/'
max_epoch: 300
batch_size: 16
learning_rate: 1e-5
num_workers: 4
dataset: 'mnist'
method: 'wronglabel'
random_seed: 1