checkpoint_dir: '$ROOT_DIR/src/embedding_preparation/checkpoints/'
log_dir: '$ROOT_DIR/src/embedding_preparation/logs/'
output_save_path: '$ROOT_DIR/src/embedding_preparation/results/'
dataset_dir: '$ROOT_DIR/data/mnist/'
max_epoch: 300
batch_size: 16
learning_rate: 1e-5
learning_rate_probing: 1e-3
probing_epoch: 10
num_workers: 4
dataset: 'mnist'
method: 'simclr'
random_seed: 1