checkpoint_dir: '$ROOT_DIR/src/main_studies/training_dynamic/checkpoints/'
log_dir: '$ROOT_DIR/src/main_studies/training_dynamic/logs/'
output_save_path: '$ROOT_DIR/src/main_studies/training_dynamic/results/'
dataset_dir: '$ROOT_DIR/data/stl10/'
max_epoch: 200
batch_size: 128
learning_rate: 1e-4
learning_rate_probing: 1e-3
probing_epoch: 10
num_workers: 8
dataset: 'stl10'
method: 'simclr'
random_seed: 1
