checkpoint_dir: '$ROOT_DIR/CPSC644-toy-study/checkpoints/'
log_dir: '$ROOT_DIR/CPSC644-toy-study/logs/'
dataset_dir: '$ROOT_DIR/data/cifar100/'
output_save_path: '$ROOT_DIR/CPSC644-toy-study/results/'
max_epoch: 200
patience: 10
batch_size: 512
learning_rate: 1e-3
weight_decay: 1e-4
num_workers: 4
dataset: 'cifar100'
contrastive: 'NA'
random_seed: 2022