checkpoint_dir: '$ROOT_DIR/CPSC644-toy-study/checkpoints/'
log_dir: '$ROOT_DIR/CPSC644-toy-study/logs/'
dataset_dir: '$ROOT_DIR/data/cifar10/'
output_save_path: '$ROOT_DIR/CPSC644-toy-study/results/'
max_epoch: 1000
patience: 40
batch_size: 128
learning_rate: 1e-2
weight_decay: 1e-6
num_workers: 4
dataset: 'cifar10'
contrastive: 'simclr'
random_seed: 2022