checkpoint_dir: '$ROOT_DIR/CPSC644-toy-study/checkpoints/'
dataset_dir: '$ROOT_DIR/data/mnist/'
max_epoch: 100
batch_size: 100
learning_rate: 1e-3
weight_decay: 1e-4
num_workers: 4
dataset: 'mnist'
contrastive: 'NA'
random_seed: 2022