checkpoint_dir: '$ROOT_DIR/CPSC644-toy-study/checkpoints/'
log_dir: '$ROOT_DIR/CPSC644-toy-study/logs/'
output_save_path: '$ROOT_DIR/CPSC644-toy-study/results/'
dataset_dir: '$ROOT_DIR/data/mnist/'
max_epoch: 200
patience: 10
batch_size: 128
learning_rate: 2e-5
weight_decay: 5e-4
num_workers: 4
dataset: 'mnist'
contrastive: 'NA'
random_seed: 2022